local Remap = require("gabrielmartins.keymap")
local nnoremap = Remap.nnoremap

nnoremap("<C-p>", ":Telescope")
nnoremap("<leader>fp", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ")})
end)
nnoremap("ff", function()
    require('telescope.builtin').git_files()
end)
nnoremap("<leader>ff", function()
    require('telescope.builtin').find_files()
end)
nnoremap("<leader>fw", function()
    require('telescope').extensions.git_worktree.git_worktrees()
end)
nnoremap("<leader>fm", function()
    require('telescope').extensions.git_worktree.create_git_worktree()
end)
nnoremap("<leader>fh", function()
    require('telescope.builtin').help_tags()
end)
nnoremap("<leader>gc", function()
    require('gabrielmartins.telescope').git_branches()
end)
